version: 2
jobs:
  security-checks:
    working_directory: ~/repo
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: sh ci/security-checks.sh && pwd
      - store_artifacts:
          path: /tmp/artifacts/hawkeye_report.json
  build:
    working_directory: ~/repo
    docker:
      - image: docker:stable
    steps:
      - run:
          command: docker build -t gcr.io/newproject-259011/myapp:${CIRCLE_BUILD_NUM} .
  push:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          command: echo $GCLOUD_SERVICE_KEY_GCR | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json && gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json && docker push gcr.io/newproject-259011/myapp:${CIRCLE_BUILD_NUM}

workflows:
  version: 2
  build-test:
    jobs:
      - security-checks
      - build:
          requires:
            - security-checks
      - push:
          requires:
            - build
